package com.mygdx.game.controlador;

public enum StuffList {

	//Caramelos normales
	CARAMELO_NORMAL_AMARILLO,
	CARAMELO_NORMAL_AZUL,
	CARAMELO_NORMAL_ROJO,
	CARAMELO_NORMAL_NARANJA,
	CARAMELO_NORMAL_VERDE,
	CARAMELO_NORMAL_MORADO,
	
	//Caramelos rallados H
	CARAMELO_RALLADO_H_AMARILLO,
	CARAMELO_RALLADO_H_AZUL,
	CARAMELO_RALLADO_H_ROJO,
	CARAMELO_RALLADO_H_NARANJA,
	CARAMELO_RALLADO_H_VERDE,
	CARAMELO_RALLADO_H_MORADO,
	
	//Caramelos rallados V
	CARAMELO_RALLADO_V_AMARILLO,
	CARAMELO_RALLADO_V_AZUL,
	CARAMELO_RALLADO_V_ROJO,
	CARAMELO_RALLADO_V_NARANJA,
	CARAMELO_RALLADO_V_VERDE,
	CARAMELO_RALLADO_V_MORADO,
	
	//Caramelos envueltos (inactivos)
	CARAMELO_ENVUELTO_AMARILLO,
	CARAMELO_ENVUELTO_AZUL,
	CARAMELO_ENVUELTO_ROJO,
	CARAMELO_ENVUELTO_NARANJA,
	CARAMELO_ENVUELTO_VERDE,
	CARAMELO_ENVUELTO_MORADO,
	
	//Caramelos envueltos (explotando)
	CARAMELO_EXPLOTANDO_AMARILLO,
	CARAMELO_EXPLOTANDO_AZUL,
	CARAMELO_EXPLOTANDO_ROJO,
	CARAMELO_EXPLOTANDO_NARANJA,
	CARAMELO_EXPLOTANDO_VERDE,
	CARAMELO_EXPLOTANDO_MORADO,
	
	//Chuches sin color
	BOMBA_COLOR,
	CEREZA,
	CEREZA_AZUL,
	CEREZA_ROJA
}
